/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectuas;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.sql.SQLException;

/**
 *
 * @author Khairiyah N Y M (222011626)
 */
public class BuatAkun extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;
    
    /**
     * Creates new form BuatAkun
     * @param contentScrollPane
     */
    public BuatAkun(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordjLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        PasswordjTextField3 = new javax.swing.JTextField();
        UsernamejLabel2 = new javax.swing.JLabel();
        PasswordjLabel3 = new javax.swing.JLabel();
        buatAkunjButton2 = new javax.swing.JButton();
        KembalijButton3 = new javax.swing.JButton();
        UsernamejTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        PasswordjLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        PasswordjLabel4.setForeground(new java.awt.Color(255, 255, 255));
        PasswordjLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordjLabel4.setText("Masukkan Ulang Password");
        add(PasswordjLabel4);
        PasswordjLabel4.setBounds(130, 290, 240, 25);

        jPasswordField1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jPasswordField1);
        jPasswordField1.setBounds(160, 235, 180, 26);

        PasswordjTextField3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PasswordjTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(PasswordjTextField3);
        PasswordjTextField3.setBounds(160, 315, 180, 26);

        UsernamejLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        UsernamejLabel2.setForeground(new java.awt.Color(255, 255, 255));
        UsernamejLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernamejLabel2.setText("Username");
        add(UsernamejLabel2);
        UsernamejLabel2.setBounds(200, 135, 100, 25);

        PasswordjLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        PasswordjLabel3.setForeground(new java.awt.Color(255, 255, 255));
        PasswordjLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordjLabel3.setText("Password");
        add(PasswordjLabel3);
        PasswordjLabel3.setBounds(200, 210, 100, 25);

        buatAkunjButton2.setBackground(new java.awt.Color(247, 190, 0));
        buatAkunjButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        buatAkunjButton2.setText("Buat Akun");
        buatAkunjButton2.setBorderPainted(false);
        buatAkunjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatAkunjButton2ActionPerformed(evt);
            }
        });
        add(buatAkunjButton2);
        buatAkunjButton2.setBounds(175, 400, 150, 29);

        KembalijButton3.setBackground(new java.awt.Color(247, 190, 0));
        KembalijButton3.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        KembalijButton3.setText("Kembali");
        KembalijButton3.setBorderPainted(false);
        KembalijButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalijButton3ActionPerformed(evt);
            }
        });
        add(KembalijButton3);
        KembalijButton3.setBounds(200, 440, 100, 30);

        UsernamejTextField2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        UsernamejTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(UsernamejTextField2);
        UsernamejTextField2.setBounds(160, 160, 180, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\4\\PBO (P)\\Project UAS\\ProjectUAS\\buat akun.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void buatAkunjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatAkunjButton2ActionPerformed
        // TODO add your handling code here:
        User u = new User();
        u.setUsername(UsernamejTextField2.getText());
        u.setPassword(jPasswordField1.getText());
        try{
            String pwd1 = jPasswordField1.getText();
            String pwd2 = PasswordjTextField3.getText();
            if (pwd2.equals(pwd1)) {    
                Database.getInstance().buatAkun(u);
                JOptionPane.showMessageDialog(this, "Berhasil ditambahkan!");
                clearForm();
            }
            else {
                JOptionPane.showMessageDialog(this, "Periksa kembali password!");
            }
        }catch(SQLException ex){
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Username sudah digunakan", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buatAkunjButton2ActionPerformed

    private void KembalijButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalijButton3ActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new Login(contentScrollPane));
    }//GEN-LAST:event_KembalijButton3ActionPerformed

    private void clearForm(){
        UsernamejTextField2.setText("");
        jPasswordField1.setText("");
        PasswordjTextField3.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KembalijButton3;
    private javax.swing.JLabel PasswordjLabel3;
    private javax.swing.JLabel PasswordjLabel4;
    private javax.swing.JTextField PasswordjTextField3;
    private javax.swing.JLabel UsernamejLabel2;
    private javax.swing.JTextField UsernamejTextField2;
    private javax.swing.JButton buatAkunjButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
