/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectuas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import static projectuas.StartPomodoro.taskjLabel;

/**
 *
 * @author Khairiyah N Y M (222011626)
 */
public class Detail extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;
    
    /**
     * Creates new form Detail
     * @param contentScrollPane
     */
    public Detail(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SudahSelesaijButton3 = new javax.swing.JButton();
        KembalijButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        taskjLabel2 = new javax.swing.JLabel();
        notesjLabel4 = new javax.swing.JLabel();
        deadlinejLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(320, 280));
        setLayout(null);

        SudahSelesaijButton3.setBackground(new java.awt.Color(247, 190, 0));
        SudahSelesaijButton3.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        SudahSelesaijButton3.setText("Sudah Selesai");
        SudahSelesaijButton3.setBorderPainted(false);
        SudahSelesaijButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SudahSelesaijButton3ActionPerformed(evt);
            }
        });
        add(SudahSelesaijButton3);
        SudahSelesaijButton3.setBounds(40, 235, 130, 23);

        KembalijButton2.setBackground(new java.awt.Color(247, 190, 0));
        KembalijButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        KembalijButton2.setText("Kembali");
        KembalijButton2.setBorderPainted(false);
        KembalijButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalijButton2ActionPerformed(evt);
            }
        });
        add(KembalijButton2);
        KembalijButton2.setBounds(190, 235, 90, 23);

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 190, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Notes:");
        add(jLabel6);
        jLabel6.setBounds(0, 135, 320, 20);

        taskjLabel2.setFont(new java.awt.Font("Dela Gothic One", 0, 20)); // NOI18N
        taskjLabel2.setForeground(new java.awt.Color(255, 255, 255));
        taskjLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(taskjLabel2);
        taskjLabel2.setBounds(0, 13, 320, 40);

        notesjLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        notesjLabel4.setForeground(new java.awt.Color(255, 255, 255));
        notesjLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(notesjLabel4);
        notesjLabel4.setBounds(0, 153, 320, 20);

        deadlinejLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        deadlinejLabel3.setForeground(new java.awt.Color(255, 255, 255));
        deadlinejLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(deadlinejLabel3);
        deadlinejLabel3.setBounds(0, 103, 320, 20);

        jTextArea1.setBackground(new java.awt.Color(49, 57, 66));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 240, 50);

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 190, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deadline:");
        add(jLabel2);
        jLabel2.setBounds(0, 85, 320, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\4\\PBO (P)\\Project UAS\\ProjectUAS\\detail.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 320, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void KembalijButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalijButton2ActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new ToDoList(contentScrollPane));
    }//GEN-LAST:event_KembalijButton2ActionPerformed

    private void SudahSelesaijButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SudahSelesaijButton3ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin tugas telah dikerjakan?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(confirm==0){
            try {
                Selesai();
                JOptionPane.showMessageDialog(this, "Tugas berhasil dihapus");
                contentScrollPane.setViewportView(new ToDoList(contentScrollPane));
            } catch (SQLException ex) {
                Logger.getLogger(ToDoList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SudahSelesaijButton3ActionPerformed

    public static void Selesai() throws SQLException{
        Database.getInstance().hapusToDoList(taskjLabel2.getText(),Login.getUsername());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KembalijButton2;
    public static javax.swing.JButton SudahSelesaijButton3;
    public static javax.swing.JLabel deadlinejLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel notesjLabel4;
    public static javax.swing.JLabel taskjLabel2;
    // End of variables declaration//GEN-END:variables
}
