/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectuas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JScrollPane;
import javax.swing.Timer;

/**
 *
 * @author Khairiyah N Y M (222011626)
 */
public class Home extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;
    
    /**
     * Creates new form Home
     * @param contentScrollPane
     */
    public Home(JScrollPane contentScrollPane) {
        initComponents();
        Home.userjLabel2.setText(Login.getUsername());
        this.contentScrollPane = contentScrollPane;
        
        tgl();
        time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userjLabel2 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        keluarjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pomodorojButton1 = new javax.swing.JButton();
        todolistjButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        userjLabel2.setFont(new java.awt.Font("Dela Gothic One", 0, 30)); // NOI18N
        userjLabel2.setForeground(new java.awt.Color(255, 255, 255));
        userjLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(userjLabel2);
        userjLabel2.setBounds(0, 90, 460, 40);

        jam.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jam.setForeground(new java.awt.Color(255, 255, 255));
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jam);
        jam.setBounds(0, 460, 470, 20);

        tanggal.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(tanggal);
        tanggal.setBounds(0, 435, 470, 20);

        keluarjButton1.setBackground(new java.awt.Color(247, 190, 0));
        keluarjButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        keluarjButton1.setText("Log Out");
        keluarjButton1.setBorderPainted(false);
        keluarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarjButton1ActionPerformed(evt);
            }
        });
        add(keluarjButton1);
        keluarjButton1.setBounds(170, 380, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\4\\PBO (P)\\Project UAS\\ProjectUAS\\home menu2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pomodorojButton1.setText("jButton1");
        pomodorojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomodorojButton1ActionPerformed(evt);
            }
        });
        add(pomodorojButton1);
        pomodorojButton1.setBounds(50, 220, 160, 110);

        todolistjButton2.setText("jButton1");
        todolistjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todolistjButton2ActionPerformed(evt);
            }
        });
        add(todolistjButton2);
        todolistjButton2.setBounds(250, 220, 160, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void pomodorojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomodorojButton1ActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new Pomodoro(contentScrollPane));
    }//GEN-LAST:event_pomodorojButton1ActionPerformed

    private void todolistjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todolistjButton2ActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new ToDoList(contentScrollPane));
    }//GEN-LAST:event_todolistjButton2ActionPerformed

    private void keluarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarjButton1ActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new Login(contentScrollPane));
    }//GEN-LAST:event_keluarjButton1ActionPerformed

    private void tgl(){
    Date d  = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
    String dd = sdf.format(d);
    tanggal.setText(dd);
    }
    
    Timer t ;
    SimpleDateFormat st ;
    
    private void time(){
        
        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt  = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                String tt = st.format(dt);
                jam.setText(tt);
            }
        });
        t.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jam;
    private javax.swing.JButton keluarjButton1;
    private javax.swing.JButton pomodorojButton1;
    private javax.swing.JLabel tanggal;
    private javax.swing.JButton todolistjButton2;
    public static javax.swing.JLabel userjLabel2;
    // End of variables declaration//GEN-END:variables
}
