/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectuas;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.sql.SQLException;

/**
 *
 * @author Khairiyah N Y M (222011626)
 */
public class KoneksiDB extends javax.swing.JPanel {
    
    private JScrollPane contentScrollPane;
    private static boolean isConnected = false;

    /**
     * Creates new form KoneksiDB
     * @param contentScrollPane
     */
    public KoneksiDB(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        UsernamejTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DatabasejTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HostnamejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        jButton1.setBackground(new java.awt.Color(247, 190, 0));
        jButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 17)); // NOI18N
        jButton1.setText("Connect");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(195, 430, 110, 32);

        jPasswordField1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jPasswordField1);
        jPasswordField1.setBounds(150, 360, 200, 29);

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        add(jLabel5);
        jLabel5.setBounds(0, 335, 500, 25);

        UsernamejTextField3.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        UsernamejTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(UsernamejTextField3);
        UsernamejTextField3.setBounds(150, 285, 200, 29);

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Username");
        add(jLabel4);
        jLabel4.setBounds(0, 260, 500, 25);

        DatabasejTextField2.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        DatabasejTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(DatabasejTextField2);
        DatabasejTextField2.setBounds(150, 210, 200, 29);

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Database");
        add(jLabel3);
        jLabel3.setBounds(0, 185, 500, 25);

        HostnamejTextField1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        HostnamejTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(HostnamejTextField1);
        HostnamejTextField1.setBounds(150, 135, 200, 29);

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hostname");
        add(jLabel2);
        jLabel2.setBounds(0, 110, 500, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\4\\PBO (P)\\Project UAS\\ProjectUAS\\koneksidb.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Database.getInstance().getConnection(HostnamejTextField1.getText(),DatabasejTextField2.getText(),
                    UsernamejTextField3.getText(),jPasswordField1.getText());
            isConnected = true;
            JOptionPane.showMessageDialog(null, "Berhasil terkoneksi dengan database!");
            contentScrollPane.setViewportView(new SelamatDatang(contentScrollPane));
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal terkoneksi dengan database!", 
                                          "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DatabasejTextField2;
    private javax.swing.JTextField HostnamejTextField1;
    private javax.swing.JTextField UsernamejTextField3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
