/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectuas;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.sql.SQLException;

/**
 *
 * @author Khairiyah N Y M (222011626)
 */
public class Login extends javax.swing.JPanel {
    
    private JScrollPane contentScrollPane;
    private static String username;

    /**
     * Creates new form Login
     * @param contentScrollPane
     */
    public Login(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginjButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginjButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        PasswordjLabel3 = new javax.swing.JLabel();
        UsernamejTextField1 = new javax.swing.JTextField();
        UsernamejLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        loginjButton2.setBackground(new java.awt.Color(247, 190, 0));
        loginjButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        loginjButton2.setText("Buat Akun");
        loginjButton2.setBorderPainted(false);
        loginjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton2ActionPerformed(evt);
            }
        });
        add(loginjButton2);
        loginjButton2.setBounds(190, 420, 120, 29);

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Belum memiliki akun?");
        add(jLabel2);
        jLabel2.setBounds(0, 390, 500, 22);

        loginjButton1.setBackground(new java.awt.Color(247, 190, 0));
        loginjButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        loginjButton1.setText("Masuk");
        loginjButton1.setBorderPainted(false);
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });
        add(loginjButton1);
        loginjButton1.setBounds(200, 283, 100, 31);

        jPasswordField1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jPasswordField1);
        jPasswordField1.setBounds(180, 215, 140, 26);

        PasswordjLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        PasswordjLabel3.setForeground(new java.awt.Color(255, 255, 255));
        PasswordjLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordjLabel3.setText("Password");
        add(PasswordjLabel3);
        PasswordjLabel3.setBounds(200, 190, 100, 25);

        UsernamejTextField1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        UsernamejTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(UsernamejTextField1);
        UsernamejTextField1.setBounds(180, 145, 140, 26);

        UsernamejLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        UsernamejLabel2.setForeground(new java.awt.Color(255, 255, 255));
        UsernamejLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernamejLabel2.setText("Username");
        add(UsernamejLabel2);
        UsernamejLabel2.setBounds(200, 120, 100, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\4\\PBO (P)\\Project UAS\\ProjectUAS\\login.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if(Database.getInstance().login(UsernamejTextField1.getText(),jPasswordField1.getText())){
                contentScrollPane.setViewportView(new Home(contentScrollPane));
                username = UsernamejTextField1.getText();
                Home.userjLabel2.setText(username);
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal Terhubung ke Database", 
                                          "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginjButton1ActionPerformed

    private void loginjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton2ActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new BuatAkun(contentScrollPane));
    }//GEN-LAST:event_loginjButton2ActionPerformed

    public static String getUsername(){
        return username;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordjLabel3;
    private javax.swing.JLabel UsernamejLabel2;
    private javax.swing.JTextField UsernamejTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginjButton1;
    private javax.swing.JButton loginjButton2;
    // End of variables declaration//GEN-END:variables
}
