/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectuas;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khairiyah N Y M (222011626)
 */
public class Pomodoro extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;
    
    /**
     * Creates new form Pomodoro
     * @param contentScrollPane
     */
    public Pomodoro(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        tampilStartjButton2 = new javax.swing.JButton();
        StartjButton1 = new javax.swing.JButton();
        KembalijButton2 = new javax.swing.JButton();
        AddjButton2 = new javax.swing.JButton();
        ListjTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        listTable.setBackground(new java.awt.Color(49, 57, 66));
        listTable.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        listTable.setForeground(new java.awt.Color(255, 255, 255));
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Urutan Kegiatan yang Akan Dilakukan:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTable.setGridColor(new java.awt.Color(49, 57, 66));
        listTable.setSelectionBackground(new java.awt.Color(49, 57, 66));
        listTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        listTable.getTableHeader().setReorderingAllowed(false);
        listTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTableMouseClicked(evt);
            }
        });
        tableScrollPane.setViewportView(listTable);

        add(tableScrollPane);
        tableScrollPane.setBounds(20, 130, 460, 270);

        tampilStartjButton2.setBackground(new java.awt.Color(247, 190, 0));
        tampilStartjButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        tampilStartjButton2.setText("Tampilkan Kegiatan Sebelumnya");
        tampilStartjButton2.setBorderPainted(false);
        tampilStartjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilStartjButton2ActionPerformed(evt);
            }
        });
        add(tampilStartjButton2);
        tampilStartjButton2.setBounds(15, 462, 270, 23);

        StartjButton1.setBackground(new java.awt.Color(247, 190, 0));
        StartjButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        StartjButton1.setText("Mulai");
        StartjButton1.setBorderPainted(false);
        StartjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartjButton1ActionPerformed(evt);
            }
        });
        add(StartjButton1);
        StartjButton1.setBounds(300, 462, 70, 23);

        KembalijButton2.setBackground(new java.awt.Color(247, 190, 0));
        KembalijButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        KembalijButton2.setText("Kembali");
        KembalijButton2.setBorderPainted(false);
        KembalijButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalijButton2ActionPerformed(evt);
            }
        });
        add(KembalijButton2);
        KembalijButton2.setBounds(385, 462, 100, 23);

        AddjButton2.setBackground(new java.awt.Color(247, 190, 0));
        AddjButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        AddjButton2.setText("Tambahkan");
        AddjButton2.setBorderPainted(false);
        AddjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjButton2ActionPerformed(evt);
            }
        });
        add(AddjButton2);
        AddjButton2.setBounds(370, 420, 120, 30);

        ListjTextField1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        add(ListjTextField1);
        ListjTextField1.setBounds(10, 420, 350, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\4\\PBO (P)\\Project UAS\\ProjectUAS\\pomodoro1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void StartjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartjButton1ActionPerformed
        // TODO add your handling code here:
        int i = listTable.getSelectedRow();
        if (i>-1){
            DefaultTableModel dtm = (DefaultTableModel) listTable.getModel();
            String tugas = dtm.getValueAt(i,0).toString();
            contentScrollPane.setViewportView(new StartPomodoro(contentScrollPane));
            StartPomodoro.taskjLabel.setText(tugas);
        }
        if (i==-1){
            JOptionPane.showMessageDialog(null, "Belum ada kegiatan yang dipilih!");
        }
    }//GEN-LAST:event_StartjButton1ActionPerformed

    private void AddjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddjButton2ActionPerformed
        // TODO add your handling code here:
        try{ 
            if (ListjTextField1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Kegiatan belum diisi");
            }
            else{
                Database.getInstance().insertTaskPomodoro(simpanTP());
                loadTable();
                clearForm();
            }
        } catch (SQLException ex){
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal memuat kegiatan", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddjButton2ActionPerformed

    private void KembalijButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalijButton2ActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new Home(contentScrollPane));
    }//GEN-LAST:event_KembalijButton2ActionPerformed

    private void listTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listTableMouseClicked

    private void tampilStartjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilStartjButton2ActionPerformed
        // TODO add your handling code here:
        loadKegiatan(Login.getUsername());
    }//GEN-LAST:event_tampilStartjButton2ActionPerformed

    private PomodoroClass simpanTP(){
        PomodoroClass list = new PomodoroClass();
        list.setTask(ListjTextField1.getText());
        list.setUser(Login.getUsername());
        
        return list;
    }
    
    private void clearForm(){
        ListjTextField1.setText("");
    }
    
    private void loadTable(){ 
        DefaultTableModel dtm = (DefaultTableModel) listTable.getModel(); 
        dtm.addRow(new Object[]{ListjTextField1.getText()});
    }
    
    private void loadKegiatan(String user){
        DefaultTableModel dtm = (DefaultTableModel) listTable.getModel(); 
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        try{
            for(String list: Database.getInstance().getListTaskPomodoro(Login.getUsername())){
                dtm.addRow(new Object[]{list});
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal memuat kegiatan", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddjButton2;
    private javax.swing.JButton KembalijButton2;
    private javax.swing.JTextField ListjTextField1;
    private javax.swing.JButton StartjButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTable listTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton tampilStartjButton2;
    // End of variables declaration//GEN-END:variables
}
